# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-helloworld',
                'doc_host': 'https://savitharaghunathan.github.io',
                'git_url': 'https://github.com/savitharaghunathan/nbdev-helloworld',
                'lib_path': 'nbdev_helloworld'},
  'syms': {'nbdev_helloworld.core': {'nbdev_helloworld.core.foo': ('core.html#foo', 'nbdev_helloworld/core.py')}}}
